export const DMs = [
    {
        id:1,
        sender: "John Doe",
        header:"Invitation",
        message: "You have been invited to join Gaming Chat Room",
        isInvitation:true,
        isAccepted:false,
        time: "12/12/2021",
        isNew: false,
    },
    {
        id:2,
        sender: "EstinConnect Admin",
        header:"Report",
        message: "You have been reported for inappropriate behavior",
        isInvitation:false,
        time: "12/12/2021",
        isNew: false,
    },
    {
        id:3,
        sender: "John Doe",
        header:"Invitation",
        message: "You have been invited to join Gaming Chat Room",
        isInvitation:true,
        isAccepted:false,
        time: "12/12/2021",
        isNew: false,
    },
    {
        id:4,
        sender: "EstinConnect Admin",
        header:"Report",
        message: "You have been reported for inappropriate behavior",
        isInvitation:false,
        time: "12/12/2021",
        isNew: false,
    },
    {
        id:5,
        sender: "John Doe",
        header:"Invitation",
        message: "You have been invited to join Gaming Chat Room",
        isInvitation:true,
        isAccepted:false,
        time: "12/12/2021",
        isNew: false,
    },
    {
        id:6,
        sender: "EstinConnect Admin",
        header:"Report",
        message: "You have been reported for inappropriate behavior",
        isInvitation:false,
        time: "12/12/2021",
        isNew: false,
    },
    {
        id:7,
        sender: "John Doe",
        header:"Invitation",
        message: "You have been invited to join Gaming Chat Room",
        isInvitation:true,
        isAccepted:false,
        time: "12/12/2021",
        isNew: false,
    },
    {
        id:8,
        sender: "EstinConnect Admin",
        header:"Report",
        message: "You have been reported for inappropriate behavior",
        isInvitation:false,
        time: "12/12/2021",
        isNew: false,
    },
    {
        id:9,
        sender: "John Doe",
        header:"Invitation",
        message: "You have been invited to join Gaming Chat Room",
        isInvitation:true,
        isAccepted:false,
        time: "12/12/2021",
        isNew: true,
    },
    {
        id:10,
        sender: "EstinConnect Admin",
        header:"Report",
        message: "You have been reported for inappropriate behavior",
        isInvitation:false,
        time: "12/12/2021",
        isNew: true,
    },
    {
        id:11,
        sender: "John Doe",
        header:"Invitation",
        message: "You have been invited to join Gaming Chat Room",
        isInvitation:true,
        isAccepted:true,
        time: "12/12/2021",
        isNew: true,
    },
    {
        id:12,
        sender: "EstinConnect Admin",
        header:"Report",
        message: "You have been reported for inappropriate behavior",
        isInvitation:false,
        time: "12/12/2021",
        isNew: true,
    }
]